adx_h1_period: 14
adx_h1_threshold: 25
ema_periods_m15: [20, 50, 200]
ema_periods_h1: [200]
atr_period: 14
supertrend:
  atr_period: 10
  multiplier: 3.0
range_filter:
  length: 20
  atr_mult: 1.5
rsi_m15_period: 14
anti_chase_atr_mult: 0.5
score_threshold_m15: 17
heavy_required_m15: 2
heavy_required_h1: 3
snapshot_confirmations: 2
vwap_anchor: daily_utc # 00:00 UTC anchor
